### ISSUE TITLE
Cant connect to Camunda Cloud

### ISSUE THREAD

**Issue by falko** [urbanisierung/zeebetron#2]
I used the address, client id, and client secret provided by the cloud console and guessed https://login.cloud.camunda.io/oauth/token for the Authz URL. But, the Zeebe communication log
only shows `$ status for Camunda Cloud Demo` or `$ deploying to profile Camunda Cloud Demo` when I try to check the status or deploy a workflow.

**Comment by urbanisierung** [comment]
Hey @falko!

I have seen similar behavior if the entered data was once entered incorrectly. I need to improve the connection with the node client.

For a quick workaround: if all data is correct, just restart the app, that should help. If not: can you please open the console with [ctrl]-[shift]-[i] and send me the error message?

Your `authz` URL is correct.

Thanks for your feedback!

**Comment by falko** [comment]
Restarting did the trick. Thank you for your help!

It would be helpful to document the Authz URL somewhere. I had to take a screenshot from your gif and the guess how the production URL could look like. If I would have had the correct URL, it would have probably worked right away.
